### PR TITLE
Added functionality to convert tweets to csv format.

### PR DESCRIPTION
**Pull request by shwetkm**
Once tweets are in a structured(tabular) format, further analysis can be done.

### CODE REVIEW

**Comment by gokriznastic** [comment]
Hey @shwetkm thank you so much for this functionality!
Are you looking to discuss ideas and collaborate further on the project?

Thanks again.

**Comment by shwetkm** [comment]
Yup, Sure.

**Comment by gokriznastic** [comment]
@shwetkm cool! I saw your github repo's and I see you have worked on a very similar problem before.
I really liked the live visualization idea in that repo. 

Please feel free to toss any ideas you have on this thread #1

**Comment by shwetkm** [comment]
Sure. Added wordcloud.

**Comment by gokriznastic** [comment]
@shwetkm wow great! thanks again for this functionality.
I'll just test it and then merge it with master.
Also, can you tell me if you have any ideas with what else can be done with the data, apart from visualization, once the `json` is collected.

**Comment by shwetkm** [comment]
Thanks!
Many things can be done once you have the data in csv.
If you want to analyse a particular twitter handle/id then it can be done using tweets meta data like created_at, favorite_count, retweet_count and retweeted. 
Also, you can perform sentiment analysis, topic modelling, etc. on the text fields, which can give you understanding about that particular twitter handle. 
This combined analysis can give some insights like i) At what time this user usually tweets? ii) What are the topics about which this user tweets ? iii) What are the sentiments of user's tweets ? iv) At what time of the day/month user tweets about a particular topic or have some specific sentiment?

Also, similarity between twitter handles can also be found based on the similarity in meta and texts. You can use word embeddings to find similarity between texts.

**Comment by gokriznastic** [comment]
@shwetkm wow great! I'll start adding some functionalities like the ones you suggested. Thanks again for the ideas and suggestions. Do you think these can be extended if we collect tweets according to hashtags? My original idea with this project was to mine tweets during a particular event that many people follow like for example the Oscars. We collect tweets from all over the world using `#oscars` and  then convert the data to `.csv` using the functionality that you added yesterday. 

Now with the data in the right format I am trying to find a way to predict the main winners in the event given the thought that more people are going to tweet about the winners or if a side is more popular or using sentiment analysis assuming good things will be said about the winners. Also, using the location-tag in tweets we can know which parts of the world are talking about which movie or actor during the event.

What are your thoughts on that?

**Comment by shwetkm** [comment]
@gokriznastic your idea of extracting tweets based on hashtags is exciting. Similar analysis which we discussed earlier can be done on those tweets as well.
Predicting winner of events is doable but i don't think it will be accurate. As, result of competitions/events are driven by several other factors.
Location based analysis will be definitely a value add.

**Comment by gokriznastic** [comment]
Hey @shwetkm.
Yeah, I know that predicting winners outright with accuracy wouldn't work very well owing to some limitations of NLP. But in my opinion, the least we can do is track hot-topics of tweets for a live event and for that particular hot topic go on to do sentiment analysis +  location-based analysis.

Considering my previous example our code will produce insights like:
```
{topic: "movie name",
keywords: [word1, word2, word3...],
popularity: 'some metric like no. of tweets containing keywords from this topic',
locations: [USA: 'popularity metric', India: 'popularity metric']}

```

This could have applications in fields like automatic post-match analysis after popular sporting events which in turn will lead to creation of more structured dataset about events.

Your thoughts?

**Pull request merged**
